In [147]:
import numpy as np

Array Operation

Arithmetic operations

In [148]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [149]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [150]:
a1-a2

array([-5, -5, -5, -5, -5])

In [151]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [152]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [153]:
a1 // a2

array([0, 0, 0, 0, 0])

In [154]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [155]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [156]:
arr+10

array([20, 30, 40, 50])

In [157]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [158]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [159]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow copy

In [160]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [161]:
slice = a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [162]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [163]:
a[4:6]*10

array([50, 60])

In [164]:
a
b = a.copy()

In [165]:
b[0] = 99

In [166]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [167]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [168]:
A = np.array([[1,2],[2,3]])
B =np.array([[5,6],[7,8]])

In [169]:
A

array([[1, 2],
       [2, 3]])

In [170]:
B

array([[5, 6],
       [7, 8]])

In [171]:
A*B

array([[ 5, 12],
       [14, 24]])

In [172]:
A @ B

array([[19, 22],
       [31, 36]])

In [173]:
np.dot(A,B)

array([[19, 22],
       [31, 36]])

In [174]:
A.T

array([[1, 2],
       [2, 3]])

Advance Array Manipulation

Stacking Array

In [175]:
a= np.array([[1,2],[2,3]])
b= np.array([[5,6],[7,8]])

In [176]:
np.vstack((a,b))


array([[1, 2],
       [2, 3],
       [5, 6],
       [7, 8]])

In [177]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [2, 3, 7, 8]])

In [182]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [186]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [191]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [196]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]