In [71]:
import numpy as np

In [72]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [73]:
s.sum()

np.int64(405)

In [74]:
np.sum(s,axis=1)

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [75]:
b=np.sum(s,axis=1)
b==45


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [76]:
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else:  # <--- এই else টি হলো Python For-Else, লুপ কোনো break ছাড়া শেষ হলে এটি ১ বার চলে
    print("For row it is valid")

For row it is valid


In [77]:
c=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print("Sudoku is not valid")
        break
else:
        print("For colums it is valid")

For colums it is valid


In [78]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [79]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [80]:
s[0:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [81]:
block_sum = np.sum(s[0:3, 0:3])
print(block_sum)

45


for colums it is valid

In [82]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [83]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n=s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [84]:
import numpy as np
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [85]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [86]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [87]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [88]:
#Find the highest Science mark.
max(data[:,2])

np.int64(95)

In [89]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [90]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [91]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [92]:
#Find how many students are younger than 19.
data[:,]

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [94]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [97]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.
data[data[:,1] >= 80]